version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hotel-reservation-system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    image: backend-service
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hotel-reservation-system
      - SPRING_DB_USERNAME=postgres
      - SPRING_DB_PASSWORD=postgres

  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    image: frontend-service
    container_name: frontend-service
    ports:
      - "3000:3000"
